<Project Sdk="Microsoft.NET.Sdk" InitialTargets="EnsureBuildSettingsExists">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <SolutionDirPath>$(MSBuildProjectDirectory)\..\</SolutionDirPath>
    <ModsRootPath>$(SolutionDirPath)bin\$(Configuration)\Mods</ModsRootPath>
    <BuildSettingsFilePath>$(SolutionDirPath)buildSettings.yml</BuildSettingsFilePath>
    <BuildSettingsTemplatePath>$(SolutionDirPath)buildSettings_template.yml</BuildSettingsTemplatePath>
    <OutputPath>$(ModsRootPath)\biodiversityCore</OutputPath>
    <Nullable>disable</Nullable>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
  </PropertyGroup>

  <PropertyGroup Condition="Exists('$(BuildSettingsFilePath)')">
    <AquaticSubModAssetPath Condition="$([System.IO.File]::ReadAllText('$(BuildSettingsFilePath)').Contains('Aquatic: true'))">"$(SolutionDirPath)biodiversityAquatic\assets"</AquaticSubModAssetPath>
    <CropsSubModAssetPath Condition="$([System.IO.File]::ReadAllText('$(BuildSettingsFilePath)').Contains('Crops: true'))">"$(SolutionDirPath)biodiversityCrops\assets"</CropsSubModAssetPath>
    <FlowersSubModAssetPath Condition="$([System.IO.File]::ReadAllText('$(BuildSettingsFilePath)').Contains('Flowers: true'))">"$(SolutionDirPath)biodiversityCrops\assets"</FlowersSubModAssetPath>
    <HerbsSubModAssetPath Condition="$([System.IO.File]::ReadAllText('$(BuildSettingsFilePath)').Contains('Herbs: true'))">$(SolutionDirPath)biodiversityHerbs\assets</HerbsSubModAssetPath>
    <OrchardsSubModAssetPath Condition="$([System.IO.File]::ReadAllText('$(BuildSettingsFilePath)').Contains('Orchards: true'))">$(SolutionDirPath)biodiversityOrchards\assets</OrchardsSubModAssetPath>
    <ShrubsSubModAssetPath Condition="$([System.IO.File]::ReadAllText('$(BuildSettingsFilePath)').Contains('Shrubs: true'))">$(SolutionDirPath)biodiversityShrubs\assets</ShrubsSubModAssetPath>
    <TreesSubModAssetPath Condition="$([System.IO.File]::ReadAllText('$(BuildSettingsFilePath)').Contains('Trees: true'))">$(SolutionDirPath)biodiversityTrees\assets</TreesSubModAssetPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="VintagestoryAPI">
      <HintPath>$(VINTAGE_STORY)/VintagestoryAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VSSurvivalMod">
      <HintPath>$(VINTAGE_STORY)/Mods/VSSurvivalMod.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VSEssentials">
      <HintPath>$(VINTAGE_STORY)/Mods/VSEssentials.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VSCreativeMod">
      <HintPath>$(VINTAGE_STORY)/Mods/VSCreativeMod.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(VINTAGE_STORY)/Lib/Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(VINTAGE_STORY)/Lib/0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VintagestoryLib">
      <HintPath>$(VINTAGE_STORY)/VintagestoryLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

<ItemGroup>
  <Content Include="modinfo.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
</ItemGroup>

<ItemGroup>
  <Content Include="modicon.png" Condition="Exists('modicon.png')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
</ItemGroup>

<ItemGroup>
  <AquaticModFiles Include="$(SolutionDirPath)biodiversityAquatic\*.*" />
  <CropsModFiles Include="$(SolutionDirPath)biodiversityCrops\*.*" />
  <FlowersModFiles Include="$(SolutionDirPath)biodiversityFlowers\*.*" />
  <HerbsModFiles Include="$(SolutionDirPath)biodiversityHerbs\*.*" />
  <OrchardsModFiles Include="$(SolutionDirPath)biodiversityOrchards\*.*" />
  <ShrubsModFiles Include="$(SolutionDirPath)biodiversityShrubs\*.*" />
  <TreesModFiles Include="$(SolutionDirPath)biodiversityTrees\*.*" />
</ItemGroup>

<Target Name="EnsureBuildSettingsExists" Condition="!Exists('$(BuildSettingsFilePath)')">
  <Copy SourceFiles="$(BuildSettingsTemplatePath)" DestinationFiles="$(BuildSettingsFilePath)" />
</Target>

<Target Name="ClearOutputFolder" AfterTargets="PostBuildEvent">
  <RemoveDir Directories="$(ModsRootPath)\biodiversityAquatic" />
  <RemoveDir Directories="$(ModsRootPath)\biodiversityCrops" />
  <RemoveDir Directories="$(ModsRootPath)\biodiversityFlowers" />
  <RemoveDir Directories="$(ModsRootPath)\biodiversityHerbs" />
  <RemoveDir Directories="$(ModsRootPath)\biodiversityOrchards" />
  <RemoveDir Directories="$(ModsRootPath)\biodiversityShrubs" />
  <RemoveDir Directories="$(ModsRootPath)\biodiversityTrees" />
</Target>

<Target Name="CopySubMods" AfterTargets="ClearOutputFolder">
  <Copy Condition="$([System.IO.File]::ReadAllText('$(BuildSettingsFilePath)').Contains('Aquatic: true'))" SourceFiles="@(AquaticModFiles)" DestinationFolder="$(ModsRootPath)\biodiversityAquatic" />
  <Copy Condition="$([System.IO.File]::ReadAllText('$(BuildSettingsFilePath)').Contains('Crops: true'))" SourceFiles="@(CropsModFiles)" DestinationFolder="$(ModsRootPath)\biodiversityCrops" />
  <Copy Condition="$([System.IO.File]::ReadAllText('$(BuildSettingsFilePath)').Contains('Flowers: true'))" SourceFiles="@(FlowersModFiles)" DestinationFolder="$(ModsRootPath)\biodiversityFlowers" />
  <Copy Condition="$([System.IO.File]::ReadAllText('$(BuildSettingsFilePath)').Contains('Herbs: true'))" SourceFiles="@(HerbsModFiles)" DestinationFolder="$(ModsRootPath)\biodiversityHerbs" />
  <Copy Condition="$([System.IO.File]::ReadAllText('$(BuildSettingsFilePath)').Contains('Orchards: true'))" SourceFiles="@(OrchardsModFiles)" DestinationFolder="$(ModsRootPath)\biodiversityOrchards" />
  <Copy Condition="$([System.IO.File]::ReadAllText('$(BuildSettingsFilePath)').Contains('Shrubs: true'))" SourceFiles="@(ShrubsModFiles)" DestinationFolder="$(ModsRootPath)\biodiversityShrubs" />
  <Copy Condition="$([System.IO.File]::ReadAllText('$(BuildSettingsFilePath)').Contains('Trees: true'))" SourceFiles="@(TreesModFiles)" DestinationFolder="$(ModsRootPath)\biodiversityTrees" />
</Target>

</Project>